### PR TITLE
Hacktoberfest first PR

### PR DESCRIPTION
**Pull request by Vishal2002**
Hope you will merge this soon....
Happy Hacktober

### CODE REVIEW

**Comment by Vishal2002** [comment]
Hope you will see the PR and merge it.

**Comment by thecyberbuzz** [comment]
> Hope you will see the PR and merge it.

make sure star🌟 Our repo before submit your pull request

**Comment by Vishal2002** [comment]
Starred the repo

**Comment by Vishal2002** [comment]
Hope you will merge it.

**Pull request merged**
